"""events mapping for threads

Revision ID: a49d761c8dc9
Revises: 09b8aa071028
Create Date: 2024-05-26 16:59:37.932995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a49d761c8dc9"
down_revision: Union[str, None] = "09b8aa071028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread",
        sa.Column("uid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.add_column(
        "assistantmessage",
        sa.Column("thread_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "assistantmessage", "thread", ["thread_id"], ["uid"])
    op.add_column(
        "externalevent",
        sa.Column("thread_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "externalevent", "thread", ["thread_id"], ["uid"])
    op.add_column(
        "systemmessage",
        sa.Column("thread_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "systemmessage", "thread", ["thread_id"], ["uid"])
    op.add_column(
        "toolmessage",
        sa.Column("thread_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "toolmessage", "thread", ["thread_id"], ["uid"])
    op.add_column(
        "usermessage",
        sa.Column("thread_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "usermessage", "thread", ["thread_id"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usermessage", type_="foreignkey")
    op.drop_column("usermessage", "thread_id")
    op.drop_constraint(None, "toolmessage", type_="foreignkey")
    op.drop_column("toolmessage", "thread_id")
    op.drop_constraint(None, "systemmessage", type_="foreignkey")
    op.drop_column("systemmessage", "thread_id")
    op.drop_constraint(None, "externalevent", type_="foreignkey")
    op.drop_column("externalevent", "thread_id")
    op.drop_constraint(None, "assistantmessage", type_="foreignkey")
    op.drop_column("assistantmessage", "thread_id")
    op.drop_table("thread")
    # ### end Alembic commands ###
