"""message_and_tool_calls_without_fkey

Revision ID: 92bb5e912594
Revises: 5eb287dcaad3
Create Date: 2024-06-02 14:21:12.034599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92bb5e912594'
down_revision: Union[str, None] = '5eb287dcaad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('type', sa.Enum('system_message', 'user_message', 'assistant_message', 'tool_message', 'external_event', name='eventtype'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('_user_message_persona_uid', sa.UUID(), nullable=True),
    sa.Column('_creator_uid', sa.UUID(), nullable=True),
    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
    sa.Column('_chat_id', sa.UUID(), nullable=False),
    sa.Column('_thread_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['_chat_id'], ['chat.uid'], ),
    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['_thread_id'], ['thread.uid'], ),
    sa.ForeignKeyConstraint(['_user_message_persona_uid'], ['persona.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tool_call',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('_assistant_message_uid', sa.UUID(), nullable=False),
    sa.Column('_tool_message_uid', sa.UUID(), nullable=True),
    sa.Column('_creator_uid', sa.UUID(), nullable=True),
    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
    sa.Column('_tool_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['_assistant_message_uid'], ['message.uid'], ),
    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['_tool_id'], ['tool.uid'], ),
    sa.ForeignKeyConstraint(['_tool_message_uid'], ['message.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_call')
    op.drop_table('message')
    # ### end Alembic commands ###
