"""add_user_messages_to_persona

Revision ID: fa55aa15c505
Revises: e0ec8d4b2b51
Create Date: 2024-05-25 00:10:56.028396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa55aa15c505'
down_revision: Union[str, None] = 'e0ec8d4b2b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
