"""stepped_migrations_to_avoid_colliding_models

Revision ID: 5eb287dcaad3
Revises: 76bab222cf82
Create Date: 2024-06-02 14:18:53.064237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eb287dcaad3'
down_revision: Union[str, None] = '76bab222cf82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('_creator_uid', sa.UUID(), nullable=True),
    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
    sa.Column('_project_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['_project_id'], ['project.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('thread',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_chat_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['_chat_id'], ['chat.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    op.drop_table('chat')
    # ### end Alembic commands ###
