"""init

Revision ID: 4bb96acf7278
Revises: 
Create Date: 2024-06-02 16:09:40.863685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb96acf7278'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('table_name', sa.TEXT(), nullable=False),
                    sa.Column('record_type', sa.TEXT(), nullable=False),
                    sa.Column('record_id', sa.UUID(), nullable=False),
                    sa.Column('operation', sa.TEXT(), nullable=False),
                    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('most_recent', sa.BOOLEAN(), nullable=False),
                    sa.Column('recorded_at', postgresql.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organization',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email_domain', sa.String(), nullable=True),
                    sa.Column('avatar_url', sa.String(), nullable=True),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('user',
                    sa.Column('email_address', sa.String(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('avatar_url', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.PrimaryKeyConstraint('uid'),
                    sa.UniqueConstraint('email_address')
                    )
    op.create_table('organizations_users',
                    sa.Column('_user_uid', sa.UUID(), nullable=False),
                    sa.Column('_organization_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_organization_uid'], ['organization.uid'], ),
                    sa.ForeignKeyConstraint(['_user_uid'], ['user.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('persona',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('avatar_url', sa.String(), nullable=True),
                    sa.Column('_organization_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_organization_uid'], ['organization.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('project',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('avatar_url', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('_organization_uid', sa.UUID(), nullable=False),
                    sa.Column('_creator_uid', sa.UUID(), nullable=True),
                    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_organization_uid'], ['organization.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('chat',
                    sa.Column('name', sa.TEXT(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('_creator_uid', sa.UUID(), nullable=True),
                    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
                    sa.Column('_project_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_project_uid'], ['project.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('tool',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('_project_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_project_uid'], ['project.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('thread',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('_chat_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_chat_uid'], ['chat.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('message',
                    sa.Column('type', sa.Enum('system_message', 'user_message', 'assistant_message', 'tool_message', 'external_event', name='eventtype'), nullable=False),
                    sa.Column('display_name', sa.String(), nullable=True),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('_user_message_persona_uid', sa.UUID(), nullable=True),
                    sa.Column('_creator_uid', sa.UUID(), nullable=True),
                    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
                    sa.Column('_chat_uid', sa.UUID(), nullable=False),
                    sa.Column('_thread_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_chat_uid'], ['chat.uid'], ),
                    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_thread_uid'], ['thread.uid'], ),
                    sa.ForeignKeyConstraint(['_user_message_persona_uid'], ['persona.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    op.create_table('tool_call',
                    sa.Column('request_id', sa.String(), nullable=False),
                    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('_assistant_message_uid', sa.UUID(), nullable=False),
                    sa.Column('_tool_message_uid', sa.UUID(), nullable=True),
                    sa.Column('_creator_uid', sa.UUID(), nullable=True),
                    sa.Column('_last_editor_uid', sa.UUID(), nullable=True),
                    sa.Column('_tool_uid', sa.UUID(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
                    sa.ForeignKeyConstraint(['_assistant_message_uid'], ['message.uid'], name='fk_tool_call_assistant_message_id', onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['_creator_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_last_editor_uid'], ['user.uid'], ),
                    sa.ForeignKeyConstraint(['_tool_message_uid'], ['message.uid'], name='fk_tool_call_tool_message_id', onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['_tool_uid'], ['tool.uid'], ),
                    sa.PrimaryKeyConstraint('uid')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_call')
    op.drop_table('message')
    op.drop_table('thread')
    op.drop_table('tool')
    op.drop_table('chat')
    op.drop_table('project')
    op.drop_table('persona')
    op.drop_table('organizations_users')
    op.drop_table('user')
    op.drop_table('organization')
    op.drop_table('archives')
    # ### end Alembic commands ###
