"""add_back_fkey

Revision ID: 1ea095f51abd
Revises: 92bb5e912594
Create Date: 2024-06-02 14:21:25.165426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ea095f51abd'
down_revision: Union[str, None] = '92bb5e912594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('_tool_message_tool_call_uid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'message', 'tool_call', ['_tool_message_tool_call_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', '_tool_message_tool_call_uid')
    # ### end Alembic commands ###
