"""init

Revision ID: b527d0e69eec
Revises: 
Create Date: 2024-06-01 17:53:13.813696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b527d0e69eec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.TEXT(), nullable=False),
    sa.Column('record_type', sa.TEXT(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.TEXT(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('most_recent', sa.BOOLEAN(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('thread',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('message',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('fkey_creator_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('fkey_last_editor_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('type', sa.Enum('system_message', 'user_message', 'assistant_message', 'tool_message', 'external_event', name='eventtype'), nullable=False),
    sa.Column('role', sa.Enum('user', 'system', 'assistant', 'tool', name='messagerole'), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('fkey_chat_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fkey_thread_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('private_user_message_fkey_persona_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('private_tool_message_fkey_tool_call_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['fkey_creator_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['fkey_last_editor_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('organizationsusers',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('fkey_organization_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fkey_user_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['fkey_organization_uid'], ['organization.uid'], ),
    sa.ForeignKeyConstraint(['fkey_user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('persona',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fkey_organization_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fkey_organization_uid'], ['organization.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('project',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('fkey_creator_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('fkey_last_editor_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fkey_organization_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['fkey_creator_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['fkey_last_editor_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['fkey_organization_uid'], ['organization.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('chat',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('fkey_creator_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('fkey_last_editor_uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fkey_project_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['fkey_creator_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['fkey_last_editor_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['fkey_project_uid'], ['project.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tool',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fkey_project_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['fkey_project_uid'], ['project.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('toolcall',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fkey_tool_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fkey_assistant_message_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fkey_tool_message_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['fkey_assistant_message_uid'], ['message.uid'], ),
    sa.ForeignKeyConstraint(['fkey_tool_message_uid'], ['message.uid'], ),
    sa.ForeignKeyConstraint(['fkey_tool_uid'], ['tool.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toolcall')
    op.drop_table('tool')
    op.drop_table('chat')
    op.drop_table('project')
    op.drop_table('persona')
    op.drop_table('organizationsusers')
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('thread')
    op.drop_table('organization')
    op.drop_table('archives')
    # ### end Alembic commands ###
