"""normalize_role

Revision ID: 0cef669f14b8
Revises: b527d0e69eec
Create Date: 2024-06-01 18:17:03.715967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cef669f14b8'
down_revision: Union[str, None] = 'b527d0e69eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('role', postgresql.ENUM('user', 'system', 'assistant', 'tool', name='messagerole'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
